Updated pytorch-version-tests.yml (#3461)
Failures with 1.13
```
2025-10-14T12:59:18.3797607Z =========================== short test summary info ============================
2025-10-14T12:59:18.3799199Z FAILED tests/ignite/contrib/engines/test_common.py::test_setup_clearml_logging - ValueError: ClearML configuration could not be found (missing `~/clearml.conf` or Environment CLEARML_API_HOST)
2025-10-14T12:59:18.3799722Z To get started with ClearML: setup your own `clearml-server`, or create a free account at https://app.community.clear.ml
2025-10-14T12:59:18.3800540Z FAILED tests/ignite/distributed/test_auto.py::test_dist_proxy_sampler - AssertionError: Regex pattern did not match.
2025-10-14T12:59:18.3800712Z  Regex: 'Argument sampler should have length'
2025-10-14T12:59:18.3801014Z  Input: "Sampler.__init__() missing 1 required positional argument: 'data_source'"
2025-10-14T12:59:18.3801756Z FAILED tests/ignite/engine/test_create_supervised.py::test_create_supervised_training_scalar_assignment - AttributeError: module 'torch.amp' has no attribute 'GradScaler'
2025-10-14T12:59:18.3802359Z FAILED tests/ignite/engine/test_create_supervised.py::test_create_supervised_trainer_scaler_not_amp - AttributeError: module 'torch.amp' has no attribute 'GradScaler'
2025-10-14T12:59:18.3803033Z FAILED tests/ignite/handlers/test_clearml_logger.py::test_integration - ValueError: ClearML configuration could not be found (missing `~/clearml.conf` or Environment CLEARML_API_HOST)
2025-10-14T12:59:18.3803419Z To get started with ClearML: setup your own `clearml-server`, or create a free account at https://app.community.clear.ml
2025-10-14T12:59:18.3804231Z FAILED tests/ignite/handlers/test_clearml_logger.py::test_integration_as_context_manager - ValueError: ClearML configuration could not be found (missing `~/clearml.conf` or Environment CLEARML_API_HOST)
2025-10-14T12:59:18.3804614Z To get started with ClearML: setup your own `clearml-server`, or create a free account at https://app.community.clear.ml
2025-10-14T12:59:18.3805346Z FAILED tests/ignite/handlers/test_clearml_logger.py::test_clearml_logger_getattr_method - ValueError: ClearML configuration could not be found (missing `~/clearml.conf` or Environment CLEARML_API_HOST)
2025-10-14T12:59:18.3805728Z To get started with ClearML: setup your own `clearml-server`, or create a free account at https://app.community.clear.ml
2025-10-14T12:59:18.3806466Z FAILED tests/ignite/handlers/test_clearml_logger.py::test_clearml_logger_get_task_bypass - ValueError: ClearML configuration could not be found (missing `~/clearml.conf` or Environment CLEARML_API_HOST)
2025-10-14T12:59:18.3806841Z To get started with ClearML: setup your own `clearml-server`, or create a free account at https://app.community.clear.ml
2025-10-14T12:59:18.3807407Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_compute[sample0] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3807971Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_compute[sample1] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3808524Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_compute[sample2] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3809076Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_compute[sample3] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3809635Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_compute[sample4] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3810401Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_compute[sample5] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3810967Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_compute[sample6] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3811456Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_compute[sample7] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3811996Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_integration[sample0] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3812473Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_integration[sample1] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3812941Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_integration[sample2] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3813451Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_integration[sample3] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3813909Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_integration[sample4] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3814371Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_integration[sample5] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3814824Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_integration[sample6] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3815340Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_integration[sample7] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3815870Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_distrib_update_compute[gloo_cpu-sample0] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3816391Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_distrib_update_compute[gloo_cpu-sample1] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3816913Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_distrib_update_compute[gloo_cpu-sample2] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3817425Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_distrib_update_compute[gloo_cpu-sample3] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3817950Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_distrib_update_compute[gloo_cpu-sample4] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3818473Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_distrib_update_compute[gloo_cpu-sample5] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3818987Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_distrib_update_compute[gloo_cpu-sample6] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3819509Z FAILED tests/ignite/metrics/vision/test_object_detection_map.py::test_distrib_update_compute[gloo_cpu-sample7] - TypeError: where(): argument 'other' (position 2) must be Tensor, not int
2025-10-14T12:59:18.3819632Z ======================= 32 failed, 3 warnings in 32.37s ========================
```

-
https://github.com/pytorch/ignite/actions/runs/18497027911/job/52703702677